language: go
go:
  - 1.11.x
  - 1.12.x
  - master
os:
  - linux
env:
  - GO111MODULE=on
install:
  - make build_tool
script:
  - make build
notifications:
  email:
    recipients:
      - 1172380450@qq.com
      - 9a6c5609806a@gmail.com
      - ma6254ma@163.com
    on_success: change
    on_failure: always
